steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'functions'
      - 'deploy'
      - 'coffee'
      - '--trigger-http'
      - '--runtime=go118'
      - '--entry-point=Coffee'
      - '--region=europe-west3'
      - '--project=apps-353612'
      - '--source=CoffeeFunction/.'
      - '--allow-unauthenticated'
      - '--set-env-vars=COFFEE_USER=${_COFFEE_USER},COFFEE_PASSWORD=${_COFFEE_PASSWORD}'

options:
  logging: CLOUD_LOGGING_ONLY
  dynamic_substitutions: true
